### ISSUE TITLE
issue with docker installation

### ISSUE THREAD

**Issue by demondamz** [Chewbaka69/PlexShare#13]
executed the docker install as per your docs and the docker fails to build below is an export of the error 
brilliant project 

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.17.1', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/dist-packages/compose/cli/main.py", line 952, in up
    start=not no_start
  File "/usr/lib/python2.7/dist-packages/compose/project.py", line 431, in up
    svc.ensure_image_exists(do_build=do_build)
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 318, in ensure_image_exists
    self.build()
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 923, in build
    shmsize=parse_bytes(build_opts.get('shm_size')) if build_opts.get('shm_size') else None,
TypeError: build() got an unexpected keyword argument 'stream'

**Comment by Chewbaka69** [comment]
Can you give the os and version you used please.

Can you explain to me, step by step how to reproduce it.

I will be back soon, I will check it.

**Comment by demondamz** [comment]
OS Ubuntu  
Version 18.04

From the WIKI ran  : 

cd /opt/appdata
git clone https://github.com/Chewbaka69/PlexShare.git plexshare
cd plexshare
docker-compose up -d plexshare

after running the docker compose command that is when i run into the issues.

**Comment by Chewbaka69** [comment]
Hello,

I have try localy on a Ubuntu 18.04 and no issue :/
I have push some little fix but i dont find a way to reproduce your error.

So maybe:
try to uninstall docker and docker-compose
`apt remove --purge docker docker-compose`

And try to reinstall it, for docker we follow the doc:
https://docs.docker.com/engine/install/ubuntu/

but for docker-compose maybe you can try this tutorial:
https://phoenixnap.com/kb/install-docker-compose-ubuntu

**Comment by Chewbaka69** [comment]
7 days without update, so i close your issue
